services:
  # Broker MQTT para a mensageria
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: rcon-hivemq
    ports:
      - "1883:1883"
      - "8080:8080"
    networks:
      - rcon-net
  
  # Automação e Inteligência
  n8n:
    image: n8nio/n8n:latest
    container_name: rcon-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    networks:
      - rcon-net
    volumes:
      - n8n_data:/home/node/.n8n
  
  # Interface Gráfica para Linphone e SNGREP
  desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: rcon-desktop
    ports:
      - "6080:80"
    networks:
      - rcon-net
  
  # Servidor de Telefonia IP - VERSÃO ATUALIZADA
  asterisk:
    image: andrius/asterisk:latest
    container_name: rcon-asterisk
    ports:
      - "5060:5060/udp"
      - "10000-10010:10000-10010/udp"
      - "8088:8088"
    networks:
      - rcon-net
    volumes:
      - ./asterisk_conf:/etc/asterisk
      - ./sounds:/var/lib/asterisk/sounds
    command: /usr/sbin/asterisk -f -vvvddd

networks:
  rcon-net:
    driver: bridge

volumes:
  n8n_data:
