services:
  # Broker MQTT para a mensageria
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: rcon-hivemq
    ports:
      - "1883:1883"
      - "8080:8080"
    networks:
      - rcon-net
  
  # Automação e Inteligência
  n8n:
    image: n8nio/n8n:latest
    container_name: rcon-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
    networks:
      - rcon-net
    volumes:
      - n8n_data:/home/node/.n8n
      - ./shared:/shared
  
  # Interface Gráfica para Linphone e SNGREP
  desktop:
    image: dorowu/ubuntu-desktop-lxde-vnc
    container_name: rcon-desktop
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - DISPLAY=:1
      - PULSE_SERVER=unix:/run/pulse/native  # ativa pulseaudio
      - WEBRTC_AUDIO=true                   # ativa áudio no noVNC
    ports:
      - "6080:80"
    networks:
      - rcon-net
    volumes:
      - ./pulse:/run/pulse
  
  # Servidor de Telefonia IP - VERSÃO ATUALIZADA
  asterisk:
    image: andrius/asterisk:latest
    container_name: rcon-asterisk
    ports:
      - "5060:5060/udp"
      - "10000-10010:10000-10010/udp"
      - "8088:8088"
    networks:
      - rcon-net
    volumes:
      - ./asterisk_conf:/etc/asterisk
      - ./sounds:/var/lib/asterisk/sounds
      - ./shared:/shared
    command: /usr/sbin/asterisk -f -vvvddd

## I.A local
  ollama:
    image: ollama/ollama:latest
    container_name: rcon-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - rcon-net

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: rcon-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - SERVERURL=auto                     # ou seu IP público/dominio se for externo
      - SERVERPORT=51820                   # porta UDP padrão do WireGuard
      - PEERS=5                            # quantidade máxima de clientes (celular, PC, sensor...)
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0         # rede interna da VPN (escolha livre)
    ports:
      - "51820:51820/udp"                  # porta que o WireGuard escuta (exponha no host)
    volumes:
      - ./wireguard:/config                # salva configs e chaves
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - rcon-net
 
networks:
  rcon-net:
    driver: bridge

volumes:
  n8n_data:
  ollama_data:
