[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = SGWsM3m4VGg3f5ZmbQWtDhqzaANP9Nc59FRzcLglAW0=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = 3m9JEPEfzgvgGl4RlaUkM8gsgfpOMbLWVs2dAxFAOVY=
PresharedKey = sp3I1/3zTfj7l6ZJkqEx/UqXhZDt4ImOiPhmng2aMU8=
AllowedIPs = 10.13.13.2/32

[Peer]
# peer2
PublicKey = DOnxm2TTpa9cBDR1llS429pEF+ZjIGNDQZi53/88DSA=
PresharedKey = UbQdd+XsnaCS10v6BnTNV80zkhZm3M6xgb3c1rxaXmU=
AllowedIPs = 10.13.13.3/32

[Peer]
# peer3
PublicKey = rpTy2bTmp+yjTTuJzoAIY14n5zyAxC7QVKto0zoGCzA=
PresharedKey = WF5kYZYwJ1sFQZHwQsfBQSYUf1Xs0AO9SpGu5D9OR28=
AllowedIPs = 10.13.13.4/32

[Peer]
# peer4
PublicKey = tfyZ7d2ZG79RjTnuf1nxuqrRGG8ktU8gEa6Otm/CFG0=
PresharedKey = OVgMvHgz6MqTi6O5HjCFH8D61dYeoxiWRcHZCQSdMYY=
AllowedIPs = 10.13.13.5/32

[Peer]
# peer5
PublicKey = A7yYtgKT04kX/SvbaW1X0FY1//Pd5sus/X8A1BfjEFI=
PresharedKey = 00hc4yjkcjfJqk4szN/W/qvlCdSeHOSE1QiI8o/I2lg=
AllowedIPs = 10.13.13.6/32

