[Interface]
Address = 10.13.13.2
PrivateKey = wC/99XWfpORoeYYIT66VYvTe/Jyr2fsH9A0jhg9zhGs=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = b/b5pRvGFX8ntqOsAybwQujAbfkI9Gx+Whey8fnMpwc=
PresharedKey = sp3I1/3zTfj7l6ZJkqEx/UqXhZDt4ImOiPhmng2aMU8=
Endpoint = 168.0.233.78:51820
AllowedIPs = 0.0.0.0/0, ::/0
