[Interface]
Address = 10.13.13.3
PrivateKey = AK8lWPFo69oACKGuf5i5Xf8CO12cOe8KYhL1kg7/xUw=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = b/b5pRvGFX8ntqOsAybwQujAbfkI9Gx+Whey8fnMpwc=
PresharedKey = UbQdd+XsnaCS10v6BnTNV80zkhZm3M6xgb3c1rxaXmU=
Endpoint = 168.0.233.78:51820
AllowedIPs = 0.0.0.0/0, ::/0
