[general]
static=yes
writeprotect=no

[from-internal]
; Ramal para o Linphone
exten => 1000,1,Dial(PJSIP/1000,20)
exten => 1000,2,Hangup()

; Teste de Áudio (Muito importante para o projeto)
exten => 999,1,Answer()
exten => 999,2,Playback(tt-monkeys)
exten => 999,3,Hangup()
