[modules]
autoload=yes

load => res_pjsip.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_endpoint_identifier_user.so
load => chan_pjsip.so

noload => chan_sip.so
load => res_http_websocket.so
load => res_ari.so
load => res_ari_model.so
; ... outros res_ari_* se quiser, mas esses dois bastam pro originate
